# Generated by Django 5.0.3 on 2024-03-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztaskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_job_id',
            field=models.CharField(blank=True, help_text='A unique identifier for the scheduled job, if any', max_length=64, null=True),
        ),
    ]
