# Generated by Django 5.0.3 on 2024-03-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztaskmanager', '0002_task_scheduled_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cached_next_ride',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next execution time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduling',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Initial scheduling'),
        ),
    ]
