version: '3.7'

services:
  redis:
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    image: redis:latest

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  redis_data:
    name: rqtaskmanager_redis_data
