version: '3.7'

services:
  redis:
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    image: redis:latest

volumes:
  redis_data:
    name: rqtaskmanager_redis_data
