name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10', 3.11, 3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Print environment variables
      run: echo "PYTHON_LOCATION=$PYTHON_LOCATION"
    - name: Install dependencies from pyproject.toml
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Activate virtual environment
      run: source ${{ env.pythonLocation }}/bin/activate
    - name: Check installed packages
      run: pip list
    - name: Test with Django's test framework
      run: python demoproject/manage.py test
      
