name: on release creation test and upload to PyPI

on:
  release:
    types: [created]


jobs:

  deploy:
    name: Build and publish distributions to PyPI
    runs-on: latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Configure Poetry
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}  # Using API token authentication
    - name: Build and publish to Pypi
      run: |
        poetry build
        poetry publish

